### PR TITLE
fix: validate hash_to_field DST as stringOrUint8Array (closes #57)

### LINKED ISSUE #57: hash_to_field Options#DST (UnicodeOrBytes) validated as string only
```
export function hash_to_field(msg: Uint8Array, count: number, options: Opts): bigint[][] {
  validateObject(options, {
    DST: 'string',
    p: 'bigint',
    m: 'isSafeInteger',
    k: 'isSafeInteger',
    hash: 'hash',
  });
```

### PR DESCRIPTION
**Pull request by sublimator**
No other ORed types in the validator list yet.
I suppose you could support some kinda operations for validators, but this KISS
Went with a generic name, so it can be reused for hexOrBytes too

### CODE REVIEW

File: src/abstract/hash-to-curve.ts [hunk 1]
```diff
@@ -127,7 +127,7 @@ export function expand_message_xof(
  */
 export function hash_to_field(msg: Uint8Array, count: number, options: Opts): bigint[][] {
   validateObject(options, {
-    DST: 'string',
+    DST: 'stringOrUint8Array',
```
Comment (sublimator) [inline src/abstract/hash-to-curve.ts:130]: I suppose you could make it take an array of validator keys?? and if .some(...) of them pass ??
